-- AlterTable
ALTER TABLE `User`
  ADD COLUMN `cpf` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `phone` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `cep` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `street` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `number` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `complement` VARCHAR(191) NULL,
  ADD COLUMN `neighborhood` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `city` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `state` VARCHAR(191) NOT NULL DEFAULT '';

-- CreateIndex
CREATE UNIQUE INDEX `User_cpf_key` ON `User`(`cpf`);
